[package]
name = "plan-review-feedback-handler"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
serde_json = "1"
session-tree-lib = { path = "../session-tree-lib" }
temper-wasm-sdk = { git = "https://github.com/nerdsane/temper.git", rev = "4a830f158c01358f0553e126be08d4af5fb3f6db" }
wasm-helpers = { path = "../wasm-helpers" }
