[package]
name = "plan-review-feedback-handler"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
serde_json = "1"
session-tree-lib = { path = "../session-tree-lib" }
temper-wasm-sdk = { git = "https://github.com/nerdsane/temper.git", rev = "7f6c029d034200599b8d03688229ad4a316b3303" }
wasm-helpers = { path = "../wasm-helpers" }
