[package]
name = "patrol-request-router"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "patrol_request_router"
path = "src/wasm_entry.rs"
test = false

[workspace]

[dependencies]
temper-wasm-sdk = { git = "https://github.com/nerdsane/temper.git", rev = "79894572a85e62b56ca57c5f5eb117988513ae63" }
