[package]
name = "patrol-request-router"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "patrol_request_router"
path = "src/wasm_entry.rs"
test = false

[workspace]

[dependencies]
temper-wasm-sdk = { git = "https://github.com/nerdsane/temper.git", rev = "88c9d797b398df04d845ff202738b09542817415" }
