[package]
name = "event-emitter"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
temper-wasm-sdk = { git = "https://github.com/nerdsane/temper.git", rev = "e45e8396884e1b88c0aec7711df1eeb2d858cab0" }
session-tree-lib = { path = "../../../paw-agent/wasm/session-tree-lib" }
wasm-helpers = { path = "../../../paw-agent/wasm/wasm-helpers" }
