[package]
name = "event-emitter"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
temper-wasm-sdk = { git = "https://github.com/nerdsane/temper.git", rev = "6439a8a0be134ffa37933701fb8fca140121d44d" }
session-tree-lib = { path = "../../../paw-agent/wasm/session-tree-lib" }
wasm-helpers = { path = "../../../paw-agent/wasm/wasm-helpers" }
