[package]
name = "session-recoverer"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
temper-wasm-sdk = { git = "https://github.com/nerdsane/temper.git", rev = "db9dc3f39b8342ba455f6bf3ff0fc5ec13c59571" }
session-tree-lib = { path = "../session-tree-lib" }
wasm-helpers = { path = "../wasm-helpers" }
