[package]
name = "session-orchestrator"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
temper-wasm-sdk = { git = "https://github.com/nerdsane/temper.git", rev = "eafba6abf5adf534a4b2578887252f196980b7a6" }
wasm-helpers = { path = "../../../paw-agent/wasm/wasm-helpers" }
