receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  resourcedetection:
    detectors: [env, system]
    timeout: 5s
    override: false
  resource:
    attributes:
      - key: service.name
        value: temperpaw
        action: upsert
      - key: service.namespace
        value: temperpaw
        action: upsert
      - key: team
        value: temperpaw
        action: upsert
  transform/dbm:
    error_mode: ignore
    trace_statements:
      - context: span
        statements:
          - set(attributes["span.type"], "sql") where attributes["db.system"] != nil and attributes["span.type"] == nil
  batch:
    send_batch_size: 1000
    timeout: 5s

exporters:
  datadog:
    api:
      key: ${env:DD_API_KEY}
      site: ${env:DD_SITE}
service:
  telemetry:
    logs:
      level: info
  pipelines:
    traces/apm:
      receivers: [otlp]
      processors: [resourcedetection, resource, transform/dbm, batch]
      exporters: [datadog]
    metrics:
      receivers: [otlp]
      processors: [resourcedetection, resource, batch]
      exporters: [datadog]
    logs:
      receivers: [otlp]
      processors: [resourcedetection, resource, batch]
      exporters: [datadog]
