[package]
name = "steering-checker"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
temper-wasm-sdk = { git = "https://github.com/nerdsane/temper.git", rev = "7bfb84ec1351715e4a3f961ba584a995d8792796" }
session-tree-lib = { path = "../session-tree-lib" }
wasm-helpers = { path = "../wasm-helpers" }
